NewsWebExample/ViewModels/AttachmentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsWebExample.ViewModels
{
    public class AttachmentViewModel
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
    }
}

NewsWebExample/ViewModels/NewsCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace NewsWebExample.ViewModels
{
    public class NewsCreateViewModel
    {
        [Required(ErrorMessage = "Name is required")]
        [MinLength(6)]
        [MaxLength(128)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Name is required")]
        [MinLength(16)]
        public string Content { get; set; }
        public List<TagViewModel> Tags { get; set; }
        public List<int> SelectedTags { get; set; }
        public IFormFile File { get; set; }
    }

    public class NewsEditViewModel : NewsCreateViewModel
    {
        [Required]
        public int Id { get; set; }
    }
}

NewsWebExample/ViewModels/NewsIndexViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsWebExample.ViewModels
{
    public class NewsShortViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<string> Tags { get; set; }
        public DateTime CreateDateTime { get; set; }
    }
    public class NewsIndexViewModel
    {
        public List<NewsShortViewModel> News { get; set; }
        public List<TagViewModel> Tags { get; set; }
        public int? CurrentTag { get; set; }
    }
}

NewsWebExample/ViewModels/NewsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsWebExample.ViewModels
{
    public class NewsViewModel
    {
        public int Id { get; set; }
        public DateTime NewsDate { get; set; }
        public string Name { get; set; }
        public string Content { get; set; }
        public List<TagViewModel> Tags { get; set; }
        public AttachmentViewModel Attachment { get; set; }
    }
}

NewsWebExample/ViewModels/TagCreateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;

namespace NewsWebExample.ViewModels
{
    public class TagCreateViewModel
    {
        [Required(ErrorMessage = "Name is required")]
        [MinLength(3)]
        [MaxLength(16)]
        public string Name { get; set; }

        public IFormFile File { get; set; }
    }

    public class TagEditViewModel : TagCreateViewModel
    {
        [Required]
        public int Id { get; set; }
    }
}

NewsWebExample/ViewModels/TagViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewsWebExample.ViewModels
{
    public class TagViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

NewsWebExample/Controllers/NewsController.cs
using System;
using System.IO;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using NewsWebExample.Services;
using NewsWebExample.ViewModels;

namespace NewsWebExample.Controllers
{
    public class NewsController : Controller
    {
        private INewsService NewsService { get; }
        private ITagsService TagsService { get; }
        
        public NewsController(INewsService newsService,
            ITagsService tagsService)
        {
            NewsService = newsService;
            TagsService = tagsService;
        }

        public IActionResult Index(int? tagId = null)
        {
            return View(NewsService.GetIndexViewModel(tagId));
        }

        public IActionResult Details(int id)
        {
            return View(NewsService.GetViewModel(id));
        }

        public IActionResult Create()
        {
            ViewBag.AllowedExtensions = NewsService.GetAllowedExtensions();
            return View(NewsService.GetCreateViewModel());
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(NewsCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Tags = TagsService.GetAll();
                return View(model);
            }

            try
            {
                NewsService.Create(model);
            }
            catch (ArgumentException)
            {
                ModelState.AddModelError(nameof(model.File), "This file type is prohibited");
                model.Tags = TagsService.GetAll();
                return View(model);
            }
            catch
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            return View(NewsService.GetEditViewModel(id));
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(NewsEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                model.Tags = TagsService.GetAll();
                return View(model);
            }

            try
            {
                NewsService.Edit(model);
            }
            catch (ArgumentException)
            {
                ModelState.AddModelError(nameof(model.File), "This file type is prohibited");
                model.Tags = TagsService.GetAll();
                return View(model);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            return View(NewsService.GetViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(NewsViewModel model)
        {
            try
            {
                NewsService.Delete(model);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

NewsWebExample/Controllers/TagsController.cs
using Microsoft.AspNetCore.Mvc;
using NewsWebExample.Services;
using NewsWebExample.ViewModels;

namespace NewsWebExample.Controllers
{
    public class TagsController : Controller
    {
        private ITagsService TagsService { get; }
        public TagsController(ITagsService tagsService)
        {
            TagsService = tagsService;
        }

        public IActionResult Index()
        {
            return View(TagsService.GetAll());
        }

        public IActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Create(TagCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                TagsService.Create(model);
            }
            catch
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            return View(TagsService.GetEditViewModel(id));
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult Edit(TagEditViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                TagsService.Edit(model);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            return View(TagsService.GetViewModel(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(TagViewModel model)
        {
            try
            {
                TagsService.Delete(model);
            }
            catch
            {
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }
    }
}

NewsWebExample/Views/News/Create.cshtml
@model NewsWebExample.ViewModels.NewsCreateViewModel
@{
    ViewData["Title"] = "Add news";
}

<form asp-action="Create" asp-controller="News" method="POST" 
      enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input required type="text" asp-for="Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea required type="text" asp-for="Content" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <label asp-for="Tags"></label>
    <select multiple required class="form-control" id="sel2" asp-for="SelectedTags">
        @foreach (var tag in Model.Tags)
        {
            @if (Model.SelectedTags != null && Model.SelectedTags.Any(x => x == tag.Id))
            {
                <option selected value="@tag.Id">@tag.Name</option>
            }
            else
            {
                <option value="@tag.Id">@tag.Name</option>
            }
        }
    </select>
    <div class="form-group">
        <label asp-for="File"></label>
        <input type="file" asp-for="File" class="border form-control-file"/>
        <span class="text-danger" asp-validation-for="File"></span>
    </div>
    <span class="text-danger" asp-validation-for="SelectedTags"></span>
    <button class="btn btn-success pl-4 pr-4" type="submit">Save</button>
</form>

NewsWebExample/Views/News/Delete.cshtml
@model NewsWebExample.ViewModels.NewsViewModel
@{
    ViewData["Title"] = "Delete news";
}
<h1>Are you sure that you want to delete news?</h1>
<h3>@Model.Name</h3>

<form asp-controller="News" asp-action="Delete" method="POST">
    <input asp-for="Id" type="hidden" />
    <div class="mt-3">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a role="button" asp-action="Details" asp-controller="News" asp-route-id="@Model.Id" class="btn btn-secondary">Cancel</a>
    </div>

</form>

NewsWebExample/Views/News/Details.cshtml
@model NewsWebExample.ViewModels.NewsViewModel
@{
    ViewData["Title"] = Model.Name;
}

<h1>@Model.Name</h1>
<p>News from: @Model.NewsDate.ToShortDateString()</p>

<div class="d-flex">
    <a class="btn btn-warning pl-4 pr-4 mr-3" asp-controller="News" asp-action="Edit" asp-route-id="@Model.Id">Edit</a>
    <a class="btn btn-danger pl-4 pr-4 mr-3" asp-controller="News" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
</div>

<div class="card mt-4">
    @if (Model.Attachment != null)
    {
        <img class="card-img-top" 
             src="~/@Model.Attachment.Path" 
             alt="@Model.Attachment.Name">
    }
    
    <div class="card-body">
        <h4>
            @Model.Content
        </h4>
    </div>
</div>

<div class="mt-3">
    <p>Tags:</p>
    @foreach (var tag in Model.Tags)
    {
        <a asp-controller="News" asp-action="Index" asp-route-tagId="@tag.Id" class="mr-4">@tag.Name</a>
    }
</div>

NewsWebExample/Views/News/Edit.cshtml
@model NewsWebExample.ViewModels.NewsEditViewModel
@{
    ViewData["Title"] = "Edit news";
}
<form asp-action="Edit" asp-controller="News" method="POST" enctype="multipart/form-data">
    <input asp-for="Id" type="hidden" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input required type="text" asp-for="Name" class="form-control" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="form-group">
        <label asp-for="Content"></label>
        <textarea required type="text" asp-for="Content" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Content"></span>
    </div>
    <label asp-for="Tags"></label>
    <select multiple required class="form-control" id="sel2" asp-for="SelectedTags">
        @foreach (var tag in Model.Tags)
        {
            @if (Model.SelectedTags != null && Model.SelectedTags.Any(x => x == tag.Id))
            {
                <option selected value="@tag.Id">@tag.Name</option>
            }
            else
            {
                <option value="@tag.Id">@tag.Name</option>
            }
        }
    </select>
    <div class="form-group">
        <label asp-for="File"></label>
        <input type="file" asp-for="File" class="border form-control-file" />
        <span class="text-danger" asp-validation-for="File"></span>
    </div>
    <span class="text-danger" asp-validation-for="SelectedTags"></span>
    <button class="btn btn-success pl-4 pr-4" type="submit">Save</button>
</form>

NewsWebExample/Views/News/Index.cshtml
@model NewsWebExample.ViewModels.NewsIndexViewModel
@{
    ViewData["Title"] = "News page";
}

<h1>News list for @(Model.CurrentTag != null ? Model.Tags.First(x => x.Id == Model.CurrentTag).Name : "All tags")</h1>

<div class="d-flex mb-4">
    <div class="dropdown">
        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Filter by tag
        </button>
        <div class="dropdown-menu">
            <a class="dropdown-item" asp-action="Index" asp-route-tagId="@null">All</a>
            @foreach (var tag in Model.Tags)
            {
                <a class="dropdown-item" asp-action="Index" asp-route-tagId="@tag.Id">@tag.Name</a>
            }
        </div>
    </div>
    <a class="btn btn-success pl-4 pr-4 ml-4"
       asp-action="Create">Add news</a>
</div>


@if (Model.News.Any())
{
    <div class="list-group">
        @foreach (var news in Model.News)
        {
            <a class="list-group-item list-group-item-action" asp-controller="News" asp-action="Details" asp-route-id="@news.Id">
                <h4>@news.Name</h4>
                <div>
                    @foreach (var tag in news.Tags)
                    {
                        <span class="badge badge-primary">@tag</span>
                    }
                </div>
                <p>@news.CreateDateTime.ToShortDateString()</p>
            </a>
        }
    </div>
}
else
{
    <div class="alert alert-info">
        List of news is empty!
    </div>
}

NewsWebExample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="News" asp-action="Index">News web site</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="News" asp-action="Index">News</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tags" asp-action="Index">Tags</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - News web site
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

NewsWebExample/Views/Tags/Create.cshtml
@model NewsWebExample.ViewModels.TagCreateViewModel
@{
    ViewData["Title"] = "Add tag";
}

@using (Html.BeginForm("Create", "Tags", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        @Html.LabelFor(x => x.Name, new { @class = "font-weight-bold" })
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label asp-for="File"></label>
        <input type="file" asp-for="File" class="border form-control-file" />
        <span class="text-danger" asp-validation-for="File"></span>
    </div>
    <button class="btn btn-success pl-4 pr-4" type="submit">Save</button>
}

NewsWebExample/Views/Tags/Delete.cshtml
@model NewsWebExample.ViewModels.TagViewModel
@{
    ViewData["Title"] = "Delete tag";
}
<h1>Are you sure that you want to delete tag?</h1>
<h3>@Model.Name</h3>

<form asp-controller="Tags" asp-action="Delete" method="POST">
    <input asp-for="Id" type="hidden" />
    <div class="mt-3">
        <button type="submit" class="btn btn-danger">Delete</button>
        <a role="button" asp-action="Index" class="btn btn-secondary">Cancel</a>
    </div>
</form>

NewsWebExample/Views/Tags/Edit.cshtml
@model NewsWebExample.ViewModels.TagEditViewModel
@{
    ViewData["Title"] = "Edit tag";
}

<form asp-action="Edit" asp-controller="Tags" method="POST" enctype="multipart/form-data">
    <input asp-for="Id" type="hidden" />
    <div class="form-group">
        <label asp-for="Name"></label>
        <input type="text" asp-for="Name" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="File"></label>
        <input type="file" asp-for="File" class="border form-control-file" />
        <span class="text-danger" asp-validation-for="File"></span>
    </div>
    <button class="btn btn-success pl-4 pr-4" type="submit">Save</button>
</form>

NewsWebExample/Views/Tags/Index.cshtml
@model List<NewsWebExample.ViewModels.TagViewModel>
@{
    ViewData["Title"] = "Tags page";
}

<h1>Tags list</h1>

<a asp-action="Create" asp-controller="Tags" class="btn btn-primary mb-3 mt-3">Create</a>

@if (Model.Any())
{
    <div class="list-group">
        @foreach (var item in Model)
        {
            <div class="list-group-item d-flex justify-content-between">
                <div>
                    @if (item.Picture != null && item.Picture.Length != 0)
                    {
                        <img width="50" height="50" 
                             src="data:image/jpeg;base64,@(Convert.ToBase64String(item.Picture))"/>
                    }
                    <span class="align-self-center"> @item.Name</span>
                </div>
                
                <div>
                    <a class="btn btn-warning btn-sm mr-2" asp-controller="Tags" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                    <a class="btn btn-danger btn-sm" asp-controller="Tags" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </div>
        }
    </div>
}
else
{
    <div class="alert alert-info">
        List of tags is empty yet!
    </div>
}

NewsWebExample/Views/Test/Index.cshtml
@using NewsWebExample.App_Code
<div class="mt-3">
    @Html.GenerateSimpleList(new List<ListItem>
    {
        new ListItem
        {
            Content = "List item 1",
            Title = "Title 1"
        },
        new ListItem
        {
            Content = "List item 2",
            Title = "Title 2"
        },
        new ListItem
        {
            Content = "List item 3",
            Title = "Title 3"
        }
    })
</div>